version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: usersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
      # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/voting_db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  gateway:
    build:
      context: ./gateway
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
  auth:
    build:
      context: ./auth
    restart: always
    env_file:
      - .env

  users:
    build:
      context: ./users
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env

  voting-executor:
    build:
      context: ./voting-executor
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env

  voting-options:
    build:
      context: ./voting-options
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env

  voting-results:
    build:
      context: ./voting-results
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mysql_data:
  mongodb-data:
